name: Release

# Create a simple release and save EXE in Github
on: 
  workflow_dispatch:
    inputs:
      notes:
        type: string
        description: Release Notes

jobs:
  build-windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-windows]
    steps:
      - name: Increment Version
        uses: starburst997/increment@v2
        with:
          name: 'VERSION'
          amount: 1
          token: ${{ secrets.GH_PAT }}

      - name: Set YEAR
        run: echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
      - run: echo Year is $YEAR

      - name: Print version
        run: echo Version = $YEAR.${{ vars.VERSION }}

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      
      - name: Tag release
        run: |
          git tag v$YEAR.${{ vars.VERSION }}
          git push origin --tags

      - name: Generate Changelog
        if: ${{ inputs.notes != '' }}
        run: echo "${{ inputs.notes }}" > RELEASE.txt
        
      - name: Generate Changelog (empty)
        if: ${{ inputs.notes == '' }}
        run: echo "No notes" > RELEASE.txt

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-windows
          path: windows

      - name: Release
        uses: starburst997/action-gh-release@v2
        with:
          body_path: RELEASE.txt
          token: ${{ secrets.GH_PAT }}
          tag_name: v${{ env.YEAR }}.${{ vars.VERSION }}
          files: |
            windows/CodeSignCpp-unsigned.exe
            windows/CodeSignCpp.exe

      - name: Cleanup to avoid storage limit
        if: always()
        uses: starburst997/delete-artifact@v5
        with:
          name: build-windows